# Generated by Django 4.0.5 on 2022-06-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_slider_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='extra_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
