# Generated by Django 4.0.5 on 2022-06-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_slider_extra_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='color',
            field=models.CharField(blank=True, choices=[('BLUE', 'blue'), ('RED', 'red')], max_length=50),
        ),
    ]
