# Generated by Django 4.0.5 on 2022-06-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_slider_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='color',
            field=models.CharField(choices=[('BLUE', 'BLUE'), ('RED', 'RED')], default='BLUE', max_length=50),
        ),
    ]
