# Generated by Django 4.0.5 on 2022-06-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_alter_slider_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
