# Generated by Django 4.0.5 on 2022-06-25 20:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_slider_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
